2021-03-06 08:41:31,757 ERROR 1980 [-/127.0.0.1/-/2ms GET /api/caUser?ca_id=undefined] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'
    at Query.Sequence._packetToError (/Users/lihong/gitrep/parasitic/parasitic_api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/lihong/gitrep/parasitic/parasitic_api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/lihong/gitrep/parasitic/parasitic_api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/lihong/gitrep/parasitic/parasitic_api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/lihong/gitrep/parasitic/parasitic_api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/lihong/gitrep/parasitic/parasitic_api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/lihong/gitrep/parasitic/parasitic_api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/lihong/gitrep/parasitic/parasitic_api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Pool.query (/Users/lihong/gitrep/parasitic/parasitic_api/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/lihong/gitrep/parasitic/parasitic_api/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/lihong/gitrep/parasitic/parasitic_api/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/lihong/gitrep/parasitic/parasitic_api/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/lihong/gitrep/parasitic/parasitic_api/node_modules/ali-rds/lib/client.js:38:20)
    at RDSClient.proto.query (/Users/lihong/gitrep/parasitic/parasitic_api/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/lihong/gitrep/parasitic/parasitic_api/node_modules/co/index.js:65:19)
    at /Users/lihong/gitrep/parasitic/parasitic_api/node_modules/co/index.js:54:5
    sql: SELECT * FROM ca_user where ca_id=undefined     limit 0,1000
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'undefined' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM ca_user where ca_id=undefined     limit 0,1000"
name: "ER_BAD_FIELD_ERRORError"
pid: 1980
hostname: lihongdeMacBook-Air.local

2021-03-06 12:23:49,196 ERROR 4729 nodejs.ClusterClientNoResponseError: client no response in 4164316ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lihong/gitrep/parasitic/parasitic_api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 4729
hostname: lihongdeMacBook-Air.local

